package com.nickgroenke;

/**
 * Placeholder class generated by archetype.
 *
 * @author nickgroenke
 */
public class Placeholder {

    private final String greetName;

    public Placeholder(String greetName) {
        this.greetName = greetName;
    }

    public String helloWorld() {
        return "Hello, " + greetName;
    }
}